# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    image: mywordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always

  wp-setup:
    image: mywordpress:latest
    depends_on:
      - wordpress
    environment:
      WP_SITE_URL: "http://localhost:8000"
      WP_SITE_TITLE: "My WordPress Site"
      WP_ADMIN_USER: admin
      WP_ADMIN_PASSWORD: admin_password
      WP_ADMIN_EMAIL: admin@example.com
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    entrypoint: ["/usr/local/bin/setup.sh"]
    restart: "no"

volumes:
  db_data:
  wp_data: