# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    image: mywordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always

  wp-setup:
    build:
      context: .
      dockerfile: Dockerfile
    image: mywordpress:latest
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    entrypoint: >
      /bin/bash -c "echo 'Waiting for WordPress installation...';
      until wp core is-installed --path=/var/www/html; do sleep 5; done;
      echo 'Activating BuddyPress plugin...';
      wp plugin activate buddypress --path=/var/www/html;
      echo 'BuddyPress activated. Exiting.'"
    restart: "no"

volumes:
  db_data:
  wp_data: